
import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations = {
  en: {
    // Header
    "app.title": "AI Toolkit Pro",
    "app.subtitle": "Advanced AI tools for every creative need",
    
    // Categories
    "category.text": "Text Tools",
    "category.text.description": "Transform and enhance your text content with advanced AI capabilities",
    "category.voice": "Voice Tools",
    "category.voice.description": "Powerful voice processing tools to enhance audio content and communication",
    "category.image": "Image Tools",
    "category.image.description": "Transform, enhance, and extract information from images with powerful AI",
    "category.video": "Video Tools",
    "category.video.description": "Create, edit, and enhance video content with cutting-edge AI technology",
    
    // Text Tools
    "tool.article-generator": "Article Generator",
    "tool.article-generator.description": "Generate well-structured articles on any topic with our advanced AI model",
    "tool.chatbot-builder": "Chatbot Builder",
    "tool.chatbot-builder.description": "Create customized AI chatbots for your website or application",
    "tool.code-generator": "Code Generator",
    "tool.code-generator.description": "Generate code snippets or complete functions based on your description",
    "tool.language-translator": "Language Translator",
    "tool.language-translator.description": "Translate text between over 100 languages with high accuracy",
    
    // Voice Tools
    "tool.text-to-speech": "Text to Speech",
    "tool.text-to-speech.description": "Convert written text into natural-sounding speech with multiple voice options",
    "tool.speech-recognition": "Speech Recognition",
    "tool.speech-recognition.description": "Convert spoken words into text with our high-accuracy speech recognition system",
    "tool.music-generator": "Music Generator",
    "tool.music-generator.description": "Create original music clips based on your description and preferences",
    
    // Image Tools
    "tool.image-to-text": "Image to Text",
    "tool.image-to-text.description": "Extract text from images using advanced OCR technology",
    "tool.image-generator": "Image Generator",
    "tool.image-generator.description": "Create unique images from textual descriptions with AI",
    "tool.image-style-transfer": "Image Style Transfer",
    "tool.image-style-transfer.description": "Apply artistic styles to your images with AI-powered style transfer",
    
    // Video Tools
    "tool.video-generator": "Video Generator",
    "tool.video-generator.description": "Create short videos from text descriptions or script outlines",
    "tool.video-summarizer": "Video Summarizer",
    "tool.video-summarizer.description": "Generate concise summaries of video content with key points highlighted",
    "tool.video-editor": "Video Editor",
    "tool.video-editor.description": "Edit and enhance videos with AI-powered effects and transformations",
    
    // Common
    "button.try-now": "Try Now",
    "button.coming-soon": "Coming Soon",
    "message.coming-soon": "This tool is coming soon! Stay tuned for updates.",
    "footer.copyright": "© 2025 AI Toolkit Pro. All rights reserved.",
    "footer.powered-by": "Powered by advanced AI technologies",
    
    // Language
    "language.switch": "العربية",
    "language.changed": "Language changed to English",
    
    // Additional translations for tool interfaces
    "Generate": "Generate",
    "Generating...": "Generating...",
    "Download": "Download",
    "Copy": "Copy",
    "Please enter a description": "Please enter a description",
    "Image generated successfully": "Image generated successfully",
    "Image downloaded": "Image downloaded",
    "Create Images with AI": "Create Images with AI",
    "Generate unique images from your text descriptions": "Generate unique images from your text descriptions",
    "Image Description": "Image Description",
    "Describe the image you want to generate...": "Describe the image you want to generate...",
    "Image Size": "Image Size",
    "Generated image": "Generated image",
    "Generating your image...": "Generating your image...",
    "Generate Image": "Generate Image",
    "Explore our suite of 13 AI-powered tools to enhance your productivity, creativity, and workflow": "Explore our suite of 13 AI-powered tools to enhance your productivity, creativity, and workflow",
    
    // Image Style Transfer
    "Transfer Art Styles to Your Images": "Transfer Art Styles to Your Images",
    "Apply artistic styles to your photos to create unique visual effects": "Apply artistic styles to your photos to create unique visual effects",
    "Source Image": "Source Image",
    "Style Image": "Style Image",
    "Upload your image": "Upload your image",
    "Style Strength": "Style Strength",
    "Subtle": "Subtle",
    "Dramatic": "Dramatic",
    "Select a style preset": "Select a style preset",
    "Custom Upload": "Custom Upload",
    "Van Gogh": "Van Gogh",
    "Picasso": "Picasso",
    "Monet": "Monet",
    "Kandinsky": "Kandinsky",
    "Upload style image": "Upload style image",
    "Apply Style": "Apply Style",
    "Processing...": "Processing...",
    "Result": "Result",
    "Style transfer completed successfully": "Style transfer completed successfully",
    "Please upload a source image": "Please upload a source image",
    "Please upload a style image or select a preset": "Please upload a style image or select a preset",
    
    // Chatbot Builder
    "AI Chatbot Builder": "AI Chatbot Builder",
    "Create custom AI chatbots for your website or application": "Create custom AI chatbots for your website or application",
    "Configuration": "Configuration",
    "Knowledge Base": "Knowledge Base",
    "Test & Deploy": "Test & Deploy",
    "Chatbot Name": "Chatbot Name",
    "Enter a name for your chatbot": "Enter a name for your chatbot",
    "Personality": "Personality",
    "Select personality": "Select personality",
    "Friendly": "Friendly",
    "Professional": "Professional",
    "Casual": "Casual",
    "Humorous": "Humorous",
    "Technical": "Technical",
    "Chatbot Instructions": "Chatbot Instructions",
    "Enter detailed instructions for your chatbot's behavior and knowledge...": "Enter detailed instructions for your chatbot's behavior and knowledge...",
    "These instructions will guide your chatbot's behavior and responses.": "These instructions will guide your chatbot's behavior and responses.",
    "Save Configuration": "Save Configuration",
    "Saving...": "Saving...",
    "Add Knowledge": "Add Knowledge",
    "Enter information that your chatbot should know...": "Enter information that your chatbot should know...",
    "Add to Knowledge Base": "Add to Knowledge Base",
    "Knowledge Base Items": "Knowledge Base Items",
    "No knowledge base items yet. Add some above.": "No knowledge base items yet. Add some above.",
    "Test Your Chatbot": "Test Your Chatbot",
    "Your conversation will appear here...": "Your conversation will appear here...",
    "Type a message...": "Type a message...",
    "Deploy": "Deploy",
    "Generate an embed code to add this chatbot to your website": "Generate an embed code to add this chatbot to your website",
    "Generate Embed Code": "Generate Embed Code",
    "Preview": "Preview",
    "Your {{name}} chatbot is ready to deploy": "Your {{name}} chatbot is ready to deploy",
    "Configure and save your chatbot first": "Configure and save your chatbot first",
    "Please enter a name for your chatbot": "Please enter a name for your chatbot",
    "Chatbot saved successfully": "Chatbot saved successfully",
    "Knowledge added successfully": "Knowledge added successfully",
    "Embed code copied to clipboard": "Embed code copied to clipboard",
    "Please enter a name for your chatbot first": "Please enter a name for your chatbot first",
    
    // Code Generator
    "AI Code Generator": "AI Code Generator",
    "Generate code snippets or complete functions based on your description": "Generate code snippets or complete functions based on your description",
    "What code do you need?": "What code do you need?",
    "Describe the code you want to generate, e.g. 'A function to calculate the total price of items in a shopping cart'": "Describe the code you want to generate, e.g. 'A function to calculate the total price of items in a shopping cart'",
    "Programming Language": "Programming Language",
    "Select language": "Select language",
    "Generate Code": "Generate Code",
    "Generated Code": "Generated Code",
    "Suggestions": "Suggestions",
    "Optimize Performance": "Optimize Performance",
    "Add Error Handling": "Add Error Handling",
    "Convert to Class": "Convert to Class",
    "Code generated successfully": "Code generated successfully",
    "Code copied to clipboard": "Code copied to clipboard",
    "Code downloaded": "Code downloaded",
    "Please enter a description of the code you need": "Please enter a description of the code you need",
    "Optimize this code for better performance": "Optimize this code for better performance",
    "Add error handling to this code": "Add error handling to this code",
    "Convert this code to a class-based approach": "Convert this code to a class-based approach",
    
    // Music Generator
    "AI Music Generator": "AI Music Generator",
    "Create original music clips based on your description and preferences": "Create original music clips based on your description and preferences",
    "Music Description": "Music Description",
    "Describe the music you want to create...": "Describe the music you want to create...",
    "Genre": "Genre",
    "Select genre": "Select genre",
    "Ambient": "Ambient",
    "Electronic": "Electronic",
    "Cinematic": "Cinematic",
    "Lo-Fi": "Lo-Fi",
    "Jazz": "Jazz",
    "Rock": "Rock",
    "Classical": "Classical",
    "Mood": "Mood",
    "Select mood": "Select mood",
    "Happy": "Happy",
    "Sad": "Sad",
    "Energetic": "Energetic",
    "Relaxed": "Relaxed",
    "Suspenseful": "Suspenseful",
    "Romantic": "Romantic",
    "Duration": "Duration",
    "seconds": "seconds",
    "Generate Music": "Generate Music",
    "Your Generated Music": "Your Generated Music",
    "Creating your music masterpiece...": "Creating your music masterpiece...",
    "Your generated music will appear here": "Your generated music will appear here",
    "Music generated successfully": "Music generated successfully",
    "Music downloaded": "Music downloaded",
    "Please enter a description for your music": "Please enter a description for your music",
    
    // Video Generator
    "AI Video Generator": "AI Video Generator",
    "Create short videos from text descriptions": "Create short videos from text descriptions",
    "Video Description": "Video Description",
    "Describe the video you want to generate...": "Describe the video you want to generate...",
    "Style": "Style",
    "Select style": "Select style",
    "Resolution": "Resolution",
    "Select resolution": "Select resolution",
    "Generate Video": "Generate Video",
    "Your Generated Video": "Your Generated Video",
    "Creating your video...": "Creating your video...",
    "Your generated video will appear here": "Your generated video will appear here",
    "Video generated successfully": "Video generated successfully",
    "Video downloaded": "Video downloaded",
    "Please enter a description for your video": "Please enter a description for your video",
    "Play": "Play",
    "Pause": "Pause",
    
    // Video Summarizer
    "AI Video Summarizer": "AI Video Summarizer",
    "Generate concise summaries of video content with key points highlighted": "Generate concise summaries of video content with key points highlighted",
    "Upload or Link Video": "Upload or Link Video",
    "YouTube or Vimeo URL": "YouTube or Vimeo URL",
    "Paste video URL...": "Paste video URL...",
    "Process URL": "Process URL",
    "Or Upload Video File": "Or Upload Video File",
    "Drag & drop your video or click to browse": "Drag & drop your video or click to browse",
    "Choose File": "Choose File",
    "Process Video": "Process Video",
    "Summary Length": "Summary Length",
    "Select length": "Select length",
    "Short": "Short",
    "Medium": "Medium",
    "Detailed": "Detailed",
    "Processing your video...": "Processing your video...",
    "This may take a few minutes depending on the video length": "This may take a few minutes depending on the video length",
    "Summary": "Summary",
    "Key Points": "Key Points",
    "View Full Transcript": "View Full Transcript",
    "Download Summary": "Download Summary",
    "Your video summary will appear here": "Your video summary will appear here",
    "Upload a video or provide a URL to get started": "Upload a video or provide a URL to get started",
    "Video successfully summarized": "Video successfully summarized",
    "Copied to clipboard": "Copied to clipboard",
    "Summary downloaded": "Summary downloaded",
    "Please enter a video URL": "Please enter a video URL",
    "Please enter a valid YouTube or Vimeo URL": "Please enter a valid YouTube or Vimeo URL",
    "Please select a video file": "Please select a video file",
    "Video file selected": "Video file selected",
    "Please select a valid video file": "Please select a valid video file",
    
    // Video Editor
    "AI Video Editor": "AI Video Editor",
    "Edit and enhance videos with AI-powered effects and transformations": "Edit and enhance videos with AI-powered effects and transformations",
    "Upload Video": "Upload Video",
    "Use Sample Video": "Use Sample Video",
    "Sample video loaded": "Sample video loaded",
    "Trim Video": "Trim Video",
    "Reset": "Reset",
    "Apply Filter": "Apply Filter",
    "Select filter": "Select filter",
    "None": "None",
    "Grayscale": "Grayscale",
    "Sepia": "Sepia",
    "Vintage": "Vintage",
    "Cold": "Cold",
    "Warm": "Warm",
    "Apply Effect": "Apply Effect",
    "Select effect": "Select effect",
    "Fade In": "Fade In",
    "Fade Out": "Fade Out",
    "Slow Motion": "Slow Motion",
    "Speed Up": "Speed Up",
    "Reverse": "Reverse",
    "Apply Changes": "Apply Changes",
    "Download Edited Video": "Download Edited Video",
    "Convert to Grayscale": "Convert to Grayscale",
    "Slow Motion Effect": "Slow Motion Effect",
    "Trim First Half Only": "Trim First Half Only",
    "Cinematic Look": "Cinematic Look",
    "Change Video": "Change Video",
    "Video edited successfully": "Video edited successfully",
    "Full Transcript": "Full Transcript",
    "This video discusses the impact of artificial intelligence on modern society, focusing on ethical considerations and future applications in healthcare and education.": "This video discusses the impact of artificial intelligence on modern society, focusing on ethical considerations and future applications in healthcare and education.",
    "This educational video explores the evolving impact of artificial intelligence on modern society over the past decade. It discusses ethical considerations around AI development, highlighting concerns about privacy, bias, and job displacement. The presenter also covers promising applications in healthcare diagnostics and personalized education, concluding with policy recommendations for responsible AI governance.": "This educational video explores the evolving impact of artificial intelligence on modern society over the past decade. It discusses ethical considerations around AI development, highlighting concerns about privacy, bias, and job displacement. The presenter also covers promising applications in healthcare diagnostics and personalized education, concluding with policy recommendations for responsible AI governance.",
    "This 25-minute educational video provides a comprehensive overview of artificial intelligence's impact on modern society. The presenter, Dr. Sarah Chen, begins by tracing AI development over the past decade, emphasizing the transition from narrow to more general AI applications. The first section explores ethical considerations, with detailed examples of privacy concerns in facial recognition, algorithmic bias in hiring processes, and potential job displacement in manufacturing and service industries. The middle portion examines promising applications, with case studies of AI in medical diagnostics showing a 30% improvement in early cancer detection rates, and adaptive learning platforms that have demonstrated significant improvements in student outcomes across diverse learning environments. The final segment offers policy recommendations, including establishing independent oversight committees, requiring algorithmic transparency for high-risk applications, and creating support systems for workforce transition. The video concludes by emphasizing that responsible AI governance requires collaboration between technologists, policymakers, and the general public.": "This 25-minute educational video provides a comprehensive overview of artificial intelligence's impact on modern society. The presenter, Dr. Sarah Chen, begins by tracing AI development over the past decade, emphasizing the transition from narrow to more general AI applications. The first section explores ethical considerations, with detailed examples of privacy concerns in facial recognition, algorithmic bias in hiring processes, and potential job displacement in manufacturing and service industries. The middle portion examines promising applications, with case studies of AI in medical diagnostics showing a 30% improvement in early cancer detection rates, and adaptive learning platforms that have demonstrated significant improvements in student outcomes across diverse learning environments. The final segment offers policy recommendations, including establishing independent oversight committees, requiring algorithmic transparency for high-risk applications, and creating support systems for workforce transition. The video concludes by emphasizing that responsible AI governance requires collaboration between technologists, policymakers, and the general public.",
    "AI development has accelerated dramatically in the past decade": "AI development has accelerated dramatically in the past decade",
    "Ethical concerns include privacy issues, algorithmic bias, and job displacement": "Ethical concerns include privacy issues, algorithmic bias, and job displacement",
    "Healthcare applications show promising results in early disease detection": "Healthcare applications show promising results in early disease detection",
    "Educational AI tools can provide personalized learning experiences": "Educational AI tools can provide personalized learning experiences",
    "Responsible governance requires collaboration between multiple stakeholders": "Responsible governance requires collaboration between multiple stakeholders",
    "Full transcript of the video would appear here. This would include a timestamped, verbatim record of all spoken content from the video, allowing users to reference specific points in detail. The transcript would be searchable and could be used for further analysis or reference.": "Full transcript of the video would appear here. This would include a timestamped, verbatim record of all spoken content from the video, allowing users to reference specific points in detail. The transcript would be searchable and could be used for further analysis or reference.",
    "Video Summary": "Video Summary"
  },
  ar: {
    // Header
    "app.title": "مجموعة أدوات الذكاء الاصطناعي برو",
    "app.subtitle": "أدوات ذكاء اصطناعي متقدمة لكل احتياج إبداعي",
    
    // Categories
    "category.text": "أدوات النص",
    "category.text.description": "قم بتحويل وتحسين محتوى النص الخاص بك باستخدام قدرات الذكاء الاصطناعي المتقدمة",
    "category.voice": "أدوات الصوت",
    "category.voice.description": "أدوات معالجة صوتية قوية لتحسين المحتوى الصوتي والتواصل",
    "category.image": "أدوات الصور",
    "category.image.description": "قم بتحويل وتحسين واستخراج المعلومات من الصور باستخدام الذكاء الاصطناعي القوي",
    "category.video": "أدوات الفيديو",
    "category.video.description": "إنشاء وتحرير وتحسين محتوى الفيديو باستخدام تكنولوجيا الذكاء الاصطناعي المتطورة",
    
    // Text Tools
    "tool.article-generator": "منشئ المقالات",
    "tool.article-generator.description": "إنشاء مقالات منظمة جيدًا حول أي موضوع باستخدام نموذج الذكاء الاصطناعي المتقدم لدينا",
    "tool.chatbot-builder": "منشئ روبوت الدردشة",
    "tool.chatbot-builder.description": "إنشاء روبوتات دردشة ذكاء اصطناعي مخصصة لموقع الويب أو التطبيق الخاص بك",
    "tool.code-generator": "منشئ الكود",
    "tool.code-generator.description": "إنشاء مقتطفات الكود أو الوظائف الكاملة بناءً على وصفك",
    "tool.language-translator": "مترجم اللغات",
    "tool.language-translator.description": "ترجم النص بين أكثر من 100 لغة بدقة عالية",
    
    // Voice Tools
    "tool.text-to-speech": "تحويل النص إلى كلام",
    "tool.text-to-speech.description": "تحويل النص المكتوب إلى كلام طبيعي مع خيارات صوتية متعددة",
    "tool.speech-recognition": "التعرف على الكلام",
    "tool.speech-recognition.description": "تحويل الكلمات المنطوقة إلى نص باستخدام نظام التعرف على الكلام عالي الدقة لدينا",
    "tool.music-generator": "منشئ الموسيقى",
    "tool.music-generator.description": "إنشاء مقاطع موسيقية أصلية بناءً على وصفك وتفضيلاتك",
    
    // Image Tools
    "tool.image-to-text": "تحويل الصورة إلى نص",
    "tool.image-to-text.description": "استخراج النص من الصور باستخدام تقنية OCR المتقدمة",
    "tool.image-generator": "منشئ الصور",
    "tool.image-generator.description": "إنشاء صور فريدة من الأوصاف النصية باستخدام الذكاء الاصطناعي",
    "tool.image-style-transfer": "نقل نمط الصورة",
    "tool.image-style-transfer.description": "تطبيق أنماط فنية على صورك باستخدام نقل النمط المدعوم بالذكاء الاصطناعي",
    
    // Video Tools
    "tool.video-generator": "منشئ الفيديو",
    "tool.video-generator.description": "إنشاء مقاطع فيديو قصيرة من أوصاف نصية أو مخططات نصية",
    "tool.video-summarizer": "ملخص الفيديو",
    "tool.video-summarizer.description": "إنشاء ملخصات موجزة لمحتوى الفيديو مع إبراز النقاط الرئيسية",
    "tool.video-editor": "محرر الفيديو",
    "tool.video-editor.description": "تحرير وتحسين مقاطع الفيديو باستخدام تأثيرات وتحويلات مدعومة بالذكاء الاصطناعي",
    
    // Common
    "button.try-now": "جرب الآن",
    "button.coming-soon": "قريبًا",
    "message.coming-soon": "هذه الأداة قادمة قريبًا! ابق على اطلاع للحصول على التحديثات.",
    "footer.copyright": "© 2025 مجموعة أدوات الذكاء الاصطناعي برو. جميع الحقوق محفوظة.",
    "footer.powered-by": "مدعوم بتقنيات الذكاء الاصطناعي المتقدمة",
    
    // Language
    "language.switch": "English",
    "language.changed": "تم تغيير اللغة إلى العربية",
    
    // Additional translations for tool interfaces
    "Generate": "إنشاء",
    "Generating...": "جاري الإنشاء...",
    "Download": "تحميل",
    "Copy": "نسخ",
    "Please enter a description": "الرجاء إدخال وصف",
    "Image generated successfully": "تم إنشاء الصورة بنجاح",
    "Image downloaded": "تم تحميل الصورة",
    "Create Images with AI": "إنشاء صور باستخدام الذكاء الاصطناعي",
    "Generate unique images from your text descriptions": "إنشاء صور فريدة من الأوصاف النصية",
    "Image Description": "وصف الصورة",
    "Describe the image you want to generate...": "صف الصورة التي ترغب في إنشائها...",
    "Image Size": "حجم الصورة",
    "Generated image": "الصورة المنشأة",
    "Generating your image...": "جاري إنشاء الصورة...",
    "Generate Image": "إنشاء صورة",
    "Explore our suite of 13 AI-powered tools to enhance your productivity, creativity, and workflow": "استكشف مجموعتنا المكونة من 13 أداة مدعومة بالذكاء الاصطناعي لتعزيز إنتاجيتك وإبداعك وسير عملك",
    
    // Image Style Transfer
    "Transfer Art Styles to Your Images": "نقل الأنماط الفنية إلى صورك",
    "Apply artistic styles to your photos to create unique visual effects": "تطبيق أنماط فنية على صورك لإنشاء تأثيرات بصرية فريدة",
    "Source Image": "الصورة المصدر",
    "Style Image": "صورة النمط",
    "Upload your image": "رفع صورتك",
    "Style Strength": "قوة النمط",
    "Subtle": "خفيف",
    "Dramatic": "دراماتيكي",
    "Select a style preset": "اختر نمطًا جاهزًا",
    "Custom Upload": "رفع مخصص",
    "Van Gogh": "فان جوخ",
    "Picasso": "بيكاسو",
    "Monet": "مونيه",
    "Kandinsky": "كاندينسكي",
    "Upload style image": "رفع صورة النمط",
    "Apply Style": "تطبيق النمط",
    "Processing...": "جاري المعالجة...",
    "Result": "النتيجة",
    "Style transfer completed successfully": "تم نقل النمط بنجاح",
    "Please upload a source image": "الرجاء رفع صورة مصدر",
    "Please upload a style image or select a preset": "الرجاء رفع صورة نمط أو اختيار نمط جاهز",
    
    // Chatbot Builder
    "AI Chatbot Builder": "منشئ روبوت الدردشة بالذكاء الاصطناعي",
    "Create custom AI chatbots for your website or application": "إنشاء روبوتات دردشة ذكاء اصطناعي مخصصة لموقع الويب أو التطبيق الخاص بك",
    "Configuration": "الإعدادات",
    "Knowledge Base": "قاعدة المعرفة",
    "Test & Deploy": "اختبار ونشر",
    "Chatbot Name": "اسم روبوت الدردشة",
    "Enter a name for your chatbot": "أدخل اسمًا لروبوت الدردشة الخاص بك",
    "Personality": "الشخصية",
    "Select personality": "اختر الشخصية",
    "Friendly": "ودود",
    "Professional": "محترف",
    "Casual": "غير رسمي",
    "Humorous": "فكاهي",
    "Technical": "تقني",
    "Chatbot Instructions": "تعليمات روبوت الدردشة",
    "Enter detailed instructions for your chatbot's behavior and knowledge...": "أدخل تعليمات مفصلة لسلوك ومعرفة روبوت الدردشة الخاص بك...",
    "These instructions will guide your chatbot's behavior and responses.": "ستوجه هذه التعليمات سلوك واستجابات روبوت الدردشة الخاص بك.",
    "Save Configuration": "حفظ الإعدادات",
    "Saving...": "جاري الحفظ...",
    "Add Knowledge": "إضافة معرفة",
    "Enter information that your chatbot should know...": "أدخل المعلومات التي يجب أن يعرفها روبوت الدردشة الخاص بك...",
    "Add to Knowledge Base": "إضافة إلى قاعدة المعرفة",
    "Knowledge Base Items": "عناصر قاعدة المعرفة",
    "No knowledge base items yet. Add some above.": "لا توجد عناصر في قاعدة المعرفة حتى الآن. أضف بعضها أعلاه.",
    "Test Your Chatbot": "اختبار روبوت الدردشة الخاص بك",
    "Your conversation will appear here...": "ستظهر محادثتك هنا...",
    "Type a message...": "اكتب رسالة...",
    "Deploy": "نشر",
    "Generate an embed code to add this chatbot to your website": "إنشاء رمز تضمين لإضافة روبوت الدردشة هذا إلى موقع الويب الخاص بك",
    "Generate Embed Code": "إنشاء رمز التضمين",
    "Preview": "معاينة",
    "Your {{name}} chatbot is ready to deploy": "روبوت الدردشة {{name}} الخاص بك جاهز للنشر",
    "Configure and save your chatbot first": "قم بتكوين وحفظ روبوت الدردشة الخاص بك أولاً",
    "Please enter a name for your chatbot": "الرجاء إدخال اسم لروبوت الدردشة الخاص بك",
    "Chatbot saved successfully": "تم حفظ روبوت الدردشة بنجاح",
    "Knowledge added successfully": "تمت إضافة المعرفة بنجاح",
    "Embed code copied to clipboard": "تم نسخ رمز التضمين إلى الحافظة",
    "Please enter a name for your chatbot first": "الرجاء إدخال اسم لروبوت الدردشة الخاص بك أولاً",
    
    // Code Generator
    "AI Code Generator": "منشئ الكود بالذكاء الاصطناعي",
    "Generate code snippets or complete functions based on your description": "إنشاء مقتطفات الكود أو الوظائف الكاملة بناءً على وصفك",
    "What code do you need?": "ما هو الكود الذي تحتاجه؟",
    "Describe the code you want to generate, e.g. 'A function to calculate the total price of items in a shopping cart'": "صف الكود الذي تريد إنشاءه، مثال: 'دالة لحساب السعر الإجمالي للعناصر في سلة التسوق'",
    "Programming Language": "لغة البرمجة",
    "Select language": "اختر اللغة",
    "Generate Code": "إنشاء الكود",
    "Generated Code": "الكود المنشأ",
    "Suggestions": "اقتراحات",
    "Optimize Performance": "تحسين الأداء",
    "Add Error Handling": "إضافة معالجة الأخطاء",
    "Convert to Class": "تحويل إلى فئة",
    "Code generated successfully": "تم إنشاء الكود بنجاح",
    "Code copied to clipboard": "تم نسخ الكود إلى الحافظة",
    "Code downloaded": "تم تنزيل الكود",
    "Please enter a description of the code you need": "الرجاء إدخال وصف للكود الذي تحتاجه",
    "Optimize this code for better performance": "تحسين هذا الكود لأداء أفضل",
    "Add error handling to this code": "إضافة معالجة الأخطاء إلى هذا الكود",
    "Convert this code to a class-based approach": "تحويل هذا الكود إلى نهج قائم على الفئات",
    
    // Music Generator
    "AI Music Generator": "منشئ الموسيقى بالذكاء الاصطناعي",
    "Create original music clips based on your description and preferences": "إنشاء مقاطع موسيقية أصلية بناءً على وصفك وتفضيلاتك",
    "Music Description": "وصف الموسيقى",
    "Describe the music you want to create...": "صف الموسيقى التي تريد إنشاءها...",
    "Genre": "النوع",
    "Select genre": "اختر النوع",
    "Ambient": "هادئة",
    "Electronic": "إلكترونية",
    "Cinematic": "سينمائية",
    "Lo-Fi": "لو-فاي",
    "Jazz": "جاز",
    "Rock": "روك",
    "Classical": "كلاسيكية",
    "Mood": "المزاج",
    "Select mood": "اختر المزاج",
    "Happy": "سعيد",
    "Sad": "حزين",
    "Energetic": "نشيط",
    "Relaxed": "مسترخي",
    "Suspenseful": "مشوق",
    "Romantic": "رومانسي",
    "Duration": "المدة",
    "seconds": "ثوانٍ",
    "Generate Music": "إنشاء الموسيقى",
    "Your Generated Music": "الموسيقى المنشأة",
    "Creating your music masterpiece...": "جاري إنشاء تحفتك الموسيقية...",
    "Your generated music will appear here": "ستظهر الموسيقى المنشأة هنا",
    "Music generated successfully": "تم إنشاء الموسيقى بنجاح",
    "Music downloaded": "تم تنزيل الموسيقى",
    "Please enter a description for your music": "الرجاء إدخال وصف للموسيقى الخاصة بك",
    
    // Video Generator
    "AI Video Generator": "منشئ الفيديو بالذكاء الاصطناعي",
    "Create short videos from text descriptions": "إنشاء مقاطع فيديو قصيرة من الأوصاف النصية",
    "Video Description": "وصف الفيديو",
    "Describe the video you want to generate...": "صف الفيديو الذي تريد إنشاءه...",
    "Style": "النمط",
    "Select style": "اختر النمط",
    "Resolution": "الدقة",
    "Select resolution": "اختر الدقة",
    "Generate Video": "إنشاء الفيديو",
    "Your Generated Video": "الفيديو المنشأ",
    "Creating your video...": "جاري إنشاء الفيديو الخاص بك...",
    "Your generated video will appear here": "سيظهر الفيديو المنشأ هنا",
    "Video generated successfully": "تم إنشاء الفيديو بنجاح",
    "Video downloaded": "تم تنزيل الفيديو",
    "Please enter a description for your video": "الرجاء إدخال وصف للفيديو الخاص بك",
    "Play": "تشغيل",
    "Pause": "إيقاف مؤقت",
    
    // Video Summarizer
    "AI Video Summarizer": "ملخص الفيديو بالذكاء الاصطناعي",
    "Generate concise summaries of video content with key points highlighted": "إنشاء ملخصات موجزة لمحتوى الفيديو مع إبراز النقاط الرئيسية",
    "Upload or Link Video": "رفع أو ربط الفيديو",
    "YouTube or Vimeo URL": "رابط يوتيوب أو فيميو",
    "Paste video URL...": "لصق رابط الفيديو...",
    "Process URL": "معالجة الرابط",
    "Or Upload Video File": "أو رفع ملف فيديو",
    "Drag & drop your video or click to browse": "اسحب وأفلت الفيديو الخاص بك أو انقر للتصفح",
    "Choose File": "اختيار ملف",
    "Process Video": "معالجة الفيديو",
    "Summary Length": "طول الملخص",
    "Select length": "اختر الطول",
    "Short": "قصير",
    "Medium": "متوسط",
    "Detailed": "مفصل",
    "Processing your video...": "جاري معالجة الفيديو الخاص بك...",
    "This may take a few minutes depending on the video length": "قد يستغرق ذلك بضع دقائق حسب طول الفيديو",
    "Summary": "الملخص",
    "Key Points": "النقاط الرئيسية",
    "View Full Transcript": "عرض النص الكامل",
    "Download Summary": "تنزيل الملخص",
    "Your video summary will appear here": "سيظهر ملخص الفيديو الخاص بك هنا",
    "Upload a video or provide a URL to get started": "قم برفع فيديو أو توفير رابط للبدء",
    "Video successfully summarized": "تم تلخيص الفيديو بنجاح",
    "Copied to clipboard": "تم النسخ إلى الحافظة",
    "Summary downloaded": "تم تنزيل الملخص",
    "Please enter a video URL": "الرجاء إدخال رابط فيديو",
    "Please enter a valid YouTube or Vimeo URL": "الرجاء إدخال رابط يوتيوب أو فيميو صالح",
    "Please select a video file": "الرجاء اختيار ملف فيديو",
    "Video file selected": "تم اختيار ملف الفيديو",
    "Please select a valid video file": "الرجاء اختيار ملف فيديو صالح",
    
    // Video Editor
    "AI Video Editor": "محرر الفيديو بالذكاء الاصطناعي",
    "Edit and enhance videos with AI-powered effects and transformations": "تحرير وتحسين مقاطع الفيديو باستخدام تأثيرات وتحويلات مدعومة بالذكاء الاصطناعي",
    "Upload Video": "رفع فيديو",
    "Use Sample Video": "استخدام فيديو نموذجي",
    "Sample video loaded": "تم تحميل الفيديو النموذجي",
    "Trim Video": "قص الفيديو",
    "Reset": "إعادة تعيين",
    "Apply Filter": "تطبيق فلتر",
    "Select filter": "اختر فلتر",
    "None": "بدون",
    "Grayscale": "تدرج رمادي",
    "Sepia": "سيبيا",
    "Vintage": "قديم",
    "Cold": "بارد",
    "Warm": "دافئ",
    "Apply Effect": "تطبيق تأثير",
    "Select effect": "اختر تأثير",
    "Fade In": "تلاشي للداخل",
    "Fade Out": "تلاشي للخارج",
    "Slow Motion": "حركة بطيئة",
    "Speed Up": "تسريع",
    "Reverse": "عكس",
    "Apply Changes": "تطبيق التغييرات",
    "Download Edited Video": "تنزيل الفيديو المحرر",
    "Convert to Grayscale": "تحويل إلى تدرج رمادي",
    "Slow Motion Effect": "تأثير الحركة البطيئة",
    "Trim First Half Only": "قص النصف الأول فقط",
    "Cinematic Look": "مظهر سينمائي",
    "Change Video": "تغيير الفيديو",
    "Video edited successfully": "تم تحرير الفيديو بنجاح",
    "Full Transcript": "النص الكامل",
    "This video discusses the impact of artificial intelligence on modern society, focusing on ethical considerations and future applications in healthcare and education.": "يناقش هذا الفيديو تأثير الذكاء الاصطناعي على المجتمع الحديث، مع التركيز على الاعتبارات الأخلاقية والتطبيقات المستقبلية في الرعاية الصحية والتعليم.",
    "This educational video explores the evolving impact of artificial intelligence on modern society over the past decade. It discusses ethical considerations around AI development, highlighting concerns about privacy, bias, and job displacement. The presenter also covers promising applications in healthcare diagnostics and personalized education, concluding with policy recommendations for responsible AI governance.": "يستكشف هذا الفيديو التعليمي تأثير الذكاء الاصطناعي المتطور على المجتمع الحديث على مدى العقد الماضي. يناقش الاعتبارات الأخلاقية حول تطوير الذكاء الاصطناعي، مسلطًا الضوء على مخاوف بشأن الخصوصية والتحيز وفقدان الوظائف. يغطي المقدم أيضًا تطبيقات واعدة في التشخيصات الصحية والتعليم المخصص، ويختتم بتوصيات سياسية لحوكمة الذكاء الاصطناعي المسؤولة.",
    "This 25-minute educational video provides a comprehensive overview of artificial intelligence's impact on modern society. The presenter, Dr. Sarah Chen, begins by tracing AI development over the past decade, emphasizing the transition from narrow to more general AI applications. The first section explores ethical considerations, with detailed examples of privacy concerns in facial recognition, algorithmic bias in hiring processes, and potential job displacement in manufacturing and service industries. The middle portion examines promising applications, with case studies of AI in medical diagnostics showing a 30% improvement in early cancer detection rates, and adaptive learning platforms that have demonstrated significant improvements in student outcomes across diverse learning environments. The final segment offers policy recommendations, including establishing independent oversight committees, requiring algorithmic transparency for high-risk applications, and creating support systems for workforce transition. The video concludes by emphasizing that responsible AI governance requires collaboration between technologists, policymakers, and the general public.": "يقدم هذا الفيديو التعليمي الذي مدته 25 دقيقة نظرة شاملة عن تأثير الذكاء الاصطناعي على المجتمع الحديث. تبدأ المقدمة، الدكتورة سارة تشن، بتتبع تطور الذكاء الاصطناعي على مدى العقد الماضي، مع التأكيد على الانتقال من تطبيقات الذكاء الاصطناعي الضيقة إلى تطبيقات أكثر عمومية. يستكشف القسم الأول الاعتبارات الأخلاقية، مع أمثلة تفصيلية لمخاوف الخصوصية في التعرف على الوجه، والتحيز الخوارزمي في عمليات التوظيف، واحتمالية فقدان الوظائف في صناعات التصنيع والخدمات. يدرس الجزء الأوسط التطبيقات الواعدة، مع دراسات حالة للذكاء الاصطناعي في التشخيصات الطبية التي تظهر تحسنًا بنسبة 30٪ في معدلات الكشف المبكر عن السرطان، ومنصات التعلم التكيفية التي أظهرت تحسينات كبيرة في نتائج الطلاب عبر بيئات تعليمية متنوعة. يقدم المقطع الأخير توصيات سياسية، بما في ذلك إنشاء لجان إشراف مستقلة، وطلب شفافية الخوارزميات للتطبيقات عالية المخاطر، وإنشاء أنظمة دعم لانتقال القوى العاملة. يختتم الفيديو بالتأكيد على أن حوكمة الذكاء الاصطناعي المسؤولة تتطلب تعاونًا بين التقنيين وصانعي السياسات والجمهور العام.",
    "AI development has accelerated dramatically in the past decade": "تسارع تطوير الذكاء الاصطناعي بشكل كبير في العقد الماضي",
    "Ethical concerns include privacy issues, algorithmic bias, and job displacement": "تشمل المخاوف الأخلاقية قضايا الخصوصية والتحيز الخوارزمي وفقدان الوظائف",
    "Healthcare applications show promising results in early disease detection": "تظهر تطبيقات الرعاية الصحية نتائج واعدة في الكشف المبكر عن الأمراض",
    "Educational AI tools can provide personalized learning experiences": "يمكن لأدوات الذكاء الاصطناعي التعليمية توفير تجارب تعليمية مخصصة",
    "Responsible governance requires collaboration between multiple stakeholders": "تتطلب الحوكمة المسؤولة تعاونًا بين أصحاب المصلحة المتعددين",
    "Full transcript of the video would appear here. This would include a timestamped, verbatim record of all spoken content from the video, allowing users to reference specific points in detail. The transcript would be searchable and could be used for further analysis or reference.": "سيظهر النص الكامل للفيديو هنا. سيتضمن ذلك سجلاً حرفياً مختوماً بالوقت لكل المحتوى المنطوق من الفيديو، مما يسمح للمستخدمين بالرجوع إلى نقاط محددة بالتفصيل. يمكن البحث في النص ويمكن استخدامه لمزيد من التحليل أو المرجع.",
    "Video Summary": "ملخص الفيديو"
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
  dir: "ltr"
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Try to get the stored language from localStorage, default to "en"
  const [language, setLanguage] = useState<Language>(() => {
    const storedLanguage = localStorage.getItem("preferredLanguage");
    return (storedLanguage === "ar" ? "ar" : "en") as Language;
  });
  
  // Save language preference to localStorage when it changes
  useEffect(() => {
    localStorage.setItem("preferredLanguage", language);
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
    
    // Add RTL specific styles for Arabic
    if (language === "ar") {
      document.body.classList.add("font-arabic");
    } else {
      document.body.classList.remove("font-arabic");
    }
  }, [language]);
  
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };
  
  const contextValue: LanguageContextType = {
    language,
    setLanguage,
    t,
    dir: language === "ar" ? "rtl" : "ltr"
  };
  
  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};
