
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yumwaavhnuthuvyingjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1bXdhYXZobnV0aHV2eWluZ2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDQyMjksImV4cCI6MjA1OTk4MDIyOX0.OjotGIsWmr49dCfHIsq1Z8cP8cJly4-RM7nu80TP3V0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
